version: '3'
services:

  auth-service:
    container_name: auth-api
    networks:
      - api-network
    build:
      # context: ../../pythonProjects/CircularWood_4.0_WP1
      context: ../../golangProjects/authService
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
    depends_on:
      - postgres

  wood-api:
    container_name: wood-api
    build:
      context: ../../pythonProjects/cw4.0
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    depends_on:
      - auth-service
    networks:
      - api-network

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/postgres-data
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
