api:
  name: DR_MALCOM_AUTH_SERVICE
  version: 1.0.2
  description: "Authentication service for the use case Dr.Malcom"
  allowed_origins:
    - http://localhost:3000
    - http://localhost:5050
    - https://dr-malcom.com
  rate_limiting:
    requests_per_minute: 100
    burst: 50
  build:
    # Custom path to define where the context of the docker-compose is to include all services
    # The context of the api refers to the location where the auth-service is located
    # This would be only used when you want to run your data-service, auth-service and the application
    # inside the same docker container
    context: .

# The application you want to connect to the auth-service
custom_service:
  # Setup for the docker-compose.docker.yml file to integrate the
  # custom-service, auth-service and data-service in the same docker container
  container_name: custom-app
  build:
    # The context of the custom_service refers to the location where the your custom application is located
    context: <path/to/your/context>
    dockerfile: Dockerfile
  # Ports mapping for the docker image of your application
  ports: "5050:5000"

application:  
  client_name: dr-malcom-auth_api_v1
  cookie_domain: localhost
  domain: localhost

server:
  # This is only configured on the production server
  port: 1993
  host: "0.0.0.0"
  development_mode: true

security:
  jwt:
    secret: very-secret
    expiration_time: 3600
    issuer: localhost
    audience: localhost

# logging:
#   level: info
#   format: json
#   output: stdout

database:
  # These parameters are configured on the production server
  type: postgres
  host: localhost
  port: 5432
  user: dr-malcom-db-admin
  password: password
  dbname: dr-malcom_auth
  sslmode: disable
  timezone: UTC
  connect_timeout: 5

email_server:
  # These parameters are configured on the production server
  server_name: mailgun
  api_key: your_mailgun_api_key
  domain: your_mailgun_domain

# redis:
#   host: localhost
#   port: 6379
#   expiration_time: 86400

styles:
  header_color: "#ffff00"
  header_background: "#3300ff"
  header_font: "Ac437_Acer_VGA_8x8"
  body_font: "Unifont"
  body_color: "#3300ff"
  body_background: "#ccffff"
  header_font_size: "24px"