api:
  name: tricera_pass_auth_service
  version: 1.0.0
  description: "God creates dinosaurs! God destroys dinosaurs! God creates man! Man destroys God! Man creates dinosaurs!"
  allowed_origins:
    - http://localhost:3000
    - http://localhost:5050
    - https://dr-malcom.com
  rate_limiting:
    requests_per_minute: 100
    burst: 50

application:  
  client_name: jurassic_login_park_dino_auth_division
  cookie_domain: localhost
  domain: dr-malcom.com

server:
  port: 1993
  host: "0.0.0.0"
  development_mode: true

security:
  jwt:
    secret: TRICERATOPLESS-eb5d5e9f-86ac-4766-93e2-d760cbb86e7d
    expiration_time: 3600
    issuer: dr-malcom.com
    audience: dr-malcom.com

logging:
  level: info
  format: json
  output: stdout

database:
  type: postgres
  host: postgres
  port: 5432
  user: veloci_raptor
  password: clever_girl
  dbname: dino_division
  sslmode: disable
  timezone: UTC
  connect_timeout: 5

email_server:
  server_name: mailgun
  api_key: your_mailgun_api_key
  domain: your_mailgun_domain

redis:
  host: localhost
  port: 6379
  expiration_time: 86400

styles:
  header_color: "#ffff00"
  header_background: "#3300ff"
  header_font: "Ac437_Acer_VGA_8x8"
  body_font: "Unifont"
  body_color: "#3300ff"
  body_background: "#ccffff"
  header_font_size: "24px"