api:
  name: tricerapass-auth-service
  version: 1.0.0
  description: God creates dinosaurs. God destroys dinosaurs. God creates man. Man destroys God. Man creates dinosaurs.
  allowedOrigins:
    - http://localhost:3000
    - https://dr-malcom.com
  rateLimiting:
    requestsPerMinute: 100
    burst: 50

application:  
  clientName: Jurassic Login Park - Dino Auth Division
  cookieDomain: localhost
  domain: dr-malcom.com

server:
  port: 1993
  host: 0.0.0.0
  developmentMode: true

security:
  jwt:
    secret: TRICERATOPLESS-eb5d5e9f-86ac-4766-93e2-d760cbb86e7d
    expirationTime: 3600
    issuer: dr-malcom.com
    audience: dr-malcom.com

logging:
  level: INFO
  format: json
  output: stdout

database:
  type: postgres
  host: localhost
  port: 5432
  user: velociRaptor
  password: CLevErG!rl
  dbname: dino-division
  sslmode: disable
  timezone: UTC
  connect_timeout: 5

redis:
  host: localhost
  port: 6379
  expirationTime: 86400

styles:
  headerColor: "#ffffff"
  headerFont: "Ac437_Acer_VGA_8x8"
  bodyFont: "Unifont"
  bodyColor: "#fff"
  bodyBackground: "#3300ff"
  headerFontSize: "24px"